name: snivy_test_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.0

flutter:
  uses-material-design: true
  assets: []

dependencies:
  flutter:
    sdk: flutter

  remote_config_sdk:
    path: ../remote_config_sdk